module.exports = {
	'likes': '{ likes, number} me gusta',
	'logout':'Salir',
	'english':'Inglès',
	'spanish':'Español',
	'signup.subheading':'Regístrate para ver fotos de tus amigos',
	'signup.facebook': 'Inicia sesiòn con Facebook',
	'signup.text': 'Inicia Sesion',
	'signup.email': 'Correo electronico',
	'signup.username': 'Usuario',
	'signup.fullname': 'Nombre completo',
	'signup.password': 'Contraseña',
	'signup.call-to-action': 'Registrate',
	'signup.have-account': '¿Tienes una cuenta?',
	'signin':'Entrar',
	'signin.no-have-account': 'No tienes una cuenta',
	'language': 'Idioma',
	'upload-picture':'Subir foto',
	'upload':'subir'
}